# Generated by Django 2.2 on 2019-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190813_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='store_id',
            field=models.CharField(max_length=1000),
        ),
    ]
