# Generated by Django 2.2 on 2019-08-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=30)),
                ('store_location', models.CharField(blank=True, max_length=300)),
                ('store_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('store_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('slug', models.SlugField(max_length=100)),
                ('store_open', models.IntegerField()),
                ('store_close', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store_image',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moderator.Store_detail')),
                ('store_image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moderator.Store_detail')),
            ],
        ),
    ]
