# Generated by Django 2.2 on 2019-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_detail',
            name='store_category',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
