# Generated by Django 2.2 on 2019-08-21 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_store_detail_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_detail',
            name='store_location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
