# Generated by Django 2.2 on 2019-08-21 23:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_store_detail_store_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_detail',
            name='store_location_point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
